"""empty message

Revision ID: 79e270f6477e
Revises: 542b6a361dad
Create Date: 2022-03-28 18:51:51.872991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e270f6477e'
down_revision = '542b6a361dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nanny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('nannys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nannys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skills', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=20, scale=10), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=20, scale=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nannys_pkey')
    )
    op.drop_table('nanny')
    # ### end Alembic commands ###
