"""empty message

Revision ID: 968cdd960a06
Revises: 
Create Date: 2022-04-06 19:07:06.364439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968cdd960a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nanny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('nanny')
    # ### end Alembic commands ###
