"""empty message

Revision ID: a660a37d7ecf
Revises: 54cfabb0a0e5
Create Date: 2022-03-22 21:38:09.486498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a660a37d7ecf'
down_revision = '54cfabb0a0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parents', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='unique')
    # ### end Alembic commands ###
